# Generated by Django 6.0.4 on 2026-05-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='session_title',
            field=models.CharField(default='New Chat', max_length=255),
        ),
    ]
